#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: R
# autospec version: v27
# autospec commit: 65cf152
#
Name     : R-pbapply
Version  : 1.7.4
Release  : 58
URL      : https://ftp.osuosl.org/pub/cran/src/contrib/pbapply_1.7-4.tar.gz
Source0  : https://ftp.osuosl.org/pub/cran/src/contrib/pbapply_1.7-4.tar.gz
Summary  : Adding Progress Bar to '*apply' Functions
Group    : Development/Tools
License  : GPL-2.0+
BuildRequires : R-future
BuildRequires : buildreq-R
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
progress bar to vectorized R functions
  ('*apply'). The implementation can easily be added
  to functions where showing the progress is
  useful (e.g. bootstrap). The type and style of the
  progress bar (with percentages or remaining time)
  can be set through options.
  Supports several parallel processing backends including mirai and future.

%prep
%setup -q -n pbapply
pushd ..
cp -a pbapply buildavx2
popd
pushd ..
cp -a pbapply buildavx512
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1753108028

%install
export SOURCE_DATE_EPOCH=1753108028
rm -rf %{buildroot}
LANG=C.UTF-8
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -flto -fno-semantic-interposition "
FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -flto -fno-semantic-interposition "
AR=gcc-ar
RANLIB=gcc-ranlib
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS  -Wl,-z -Wl,relro"
mkdir -p %{buildroot}/usr/lib64/R/library
mkdir -p %{buildroot}-v3/usr/lib64/R/library
mkdir -p %{buildroot}-v4/usr/lib64/R/library
mkdir -p %{buildroot}-va/usr/lib64/R/library

mkdir -p ~/.R
echo "CFLAGS = $CFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper" > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL  --install-tests --use-LTO --built-timestamp=${SOURCE_DATE_EPOCH} --data-compress=none --compress=none --build  -l %{buildroot}-v3/usr/lib64/R/library .
echo "CFLAGS = $CFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize  -mno-vzeroupper " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize  -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL --preclean  --install-tests --use-LTO --no-test-load --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}-v4/usr/lib64/R/library .
echo "CFLAGS = $CFLAGS -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean  --use-LTO --install-tests --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library .
%{__rm} -rf %{buildroot}%{_datadir}/R/library/R.css
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export _R_CHECK_FORCE_SUGGESTS_=false
R CMD check --no-manual --no-examples --no-codoc . || :

/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}
/usr/bin/elf-move.py avx512 %{buildroot}-v4 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)
/usr/lib64/R/library/pbapply/DESCRIPTION
/usr/lib64/R/library/pbapply/INDEX
/usr/lib64/R/library/pbapply/Meta/Rd.rds
/usr/lib64/R/library/pbapply/Meta/features.rds
/usr/lib64/R/library/pbapply/Meta/hsearch.rds
/usr/lib64/R/library/pbapply/Meta/links.rds
/usr/lib64/R/library/pbapply/Meta/nsInfo.rds
/usr/lib64/R/library/pbapply/Meta/package.rds
/usr/lib64/R/library/pbapply/NAMESPACE
/usr/lib64/R/library/pbapply/NEWS.md
/usr/lib64/R/library/pbapply/R/pbapply
/usr/lib64/R/library/pbapply/R/pbapply.rdb
/usr/lib64/R/library/pbapply/R/pbapply.rdx
/usr/lib64/R/library/pbapply/WORDLIST
/usr/lib64/R/library/pbapply/help/AnIndex
/usr/lib64/R/library/pbapply/help/aliases.rds
/usr/lib64/R/library/pbapply/help/paths.rds
/usr/lib64/R/library/pbapply/help/pbapply.rdb
/usr/lib64/R/library/pbapply/help/pbapply.rdx
/usr/lib64/R/library/pbapply/html/00Index.html
/usr/lib64/R/library/pbapply/html/R.css
/usr/lib64/R/library/pbapply/tests/tests.R
